/* ═══════════ 분리수거 검사관 v2 — 데이터 (특징 21 × 물건 100) ═══════════
   스펙: llm-wiki vaults/앱-개발/topics/분리수거 검사관 아이템 조합표.md (v4)
   stage: 1=튜토리얼1풀 2=+2단계 3=+3단계 4=도전 전용(미학습 전이 측정) */

export const CATS = {
  paper: "종이류", can: "캔류", food: "음식물", plastic: "플라스틱류", trash: "재활용 안 됨",
};

// sense: eye(👀 눈) / hand(✋ 손) / nose(👃 코)
export const FEATURES = {
  red:     { name: "빨간색",           sense: "eye",  icon: "🔴" },
  blue:    { name: "파란색",           sense: "eye",  icon: "🔵" },
  yellow:  { name: "노란색",           sense: "eye",  icon: "🟡" },
  chara:   { name: "캐릭터·그림이 있어요", sense: "eye",  icon: "🐰" },
  text:    { name: "글자가 있어요",     sense: "eye",  icon: "🔤" },
  flat:    { name: "납작해요",         sense: "eye",  icon: "▭" },
  cyl:     { name: "원통형이에요",      sense: "eye",  icon: "🥫" },
  box:     { name: "상자 모양이에요",   sense: "eye",  icon: "📦" },
  shiny:   { name: "반짝여요",         sense: "eye",  icon: "✨" },
  clear:   { name: "투명해요",         sense: "eye",  icon: "🔍" },
  stain:   { name: "얼룩·기름이 묻었어요", sense: "eye", icon: "💥" },
  concave: { name: "오목해요",         sense: "eye",  icon: "🥣" },
  handle:  { name: "손잡이가 있어요",   sense: "eye",  icon: "🧺" },
  lid:     { name: "뚜껑이 있어요",     sense: "eye",  icon: "🫙" },
  hard:    { name: "딱딱해요",         sense: "hand", icon: "🧱" },
  crumple: { name: "잘 구겨져요",       sense: "hand", icon: "🫓" },
  light:   { name: "가벼워요",         sense: "hand", icon: "🪶" },
  cold:    { name: "차가워요",         sense: "hand", icon: "🧊" },
  wet:     { name: "젖어 있어요",       sense: "hand", icon: "💧" },
  fsmell:  { name: "음식 냄새가 나요",  sense: "nose", icon: "🍎" },
  stink:   { name: "고약한 냄새가 나요", sense: "nose", icon: "🤢" },
};

// { id: [이름, 분류, stage, [특징...]] }
export const ITEMS = {
  /* ── 종이류 (22) ── */
  newspaper:   ["신문지",          "paper", 1, ["flat","text","crumple","light"]],
  notebook:    ["공책",            "paper", 1, ["flat","text","crumple","blue"]],
  paperbox:    ["종이상자",        "paper", 1, ["box","text","crumple"]],
  paperbag:    ["종이봉투",        "paper", 1, ["crumple","light","text","handle"]],
  magazine:    ["잡지",            "paper", 1, ["flat","text","crumple","yellow"]],
  envelope:    ["편지봉투",        "paper", 1, ["flat","text","light","crumple"]],
  flyer:       ["전단지",          "paper", 2, ["flat","text","crumple","red","chara"]],
  calendar:    ["달력",            "paper", 2, ["flat","text","crumple"]],
  storybook:   ["동화책",          "paper", 2, ["flat","text","chara","hard"]],
  sketchbook:  ["스케치북",        "paper", 2, ["flat","text","crumple"]],
  tissuebox:   ["티슈상자",        "paper", 2, ["box","text","crumple","blue"]],
  papercore:   ["휴지심",          "paper", 2, ["cyl","light","crumple"]],
  dictionary:  ["사전",            "paper", 2, ["flat","text","hard"]],
  shoebox:     ["신발상자",        "paper", 2, ["box","text","crumple","yellow"]],
  comicbook:   ["만화책",          "paper", 3, ["flat","text","chara","crumple"]],
  testpaper:   ["시험지",          "paper", 3, ["flat","text","light","crumple"]],
  shoppingbag: ["종이쇼핑백",      "paper", 3, ["text","crumple","light","red","handle"]],
  eggcarton:   ["계란판",          "paper", 3, ["crumple","light","concave"]],
  wrapping:    ["포장지",          "paper", 3, ["crumple","chara","yellow","light"]],
  adpaper:     ["광고지",          "paper", 4, ["flat","text","crumple","blue"]],
  picturebook: ["그림책",          "paper", 4, ["flat","text","chara","hard"]],
  cardboard:   ["골판지",          "paper", 4, ["box","crumple","text"]],
  /* ── 캔류 (15) ── */
  cola:        ["콜라캔",          "can", 1, ["red","cyl","shiny","cold","hard"]],
  cider:       ["사이다캔",        "can", 1, ["blue","cyl","shiny","cold","hard"]],
  tuna:        ["참치캔",          "can", 1, ["cyl","shiny","cold","hard","flat"]],
  cannedfood:  ["통조림캔",        "can", 1, ["cyl","shiny","cold","hard","text"]],
  sikhye:      ["식혜캔",          "can", 1, ["cyl","shiny","cold","hard","yellow","text"]],
  hamcan:      ["햄통조림",        "can", 2, ["box","shiny","cold","hard","text","blue"]],
  coffeecan:   ["커피캔",          "can", 2, ["cyl","shiny","cold","hard","yellow","text"]],
  grapecan:    ["포도음료캔",      "can", 2, ["cyl","shiny","cold","hard","chara"]],
  butane:      ["부탄가스캔",      "can", 3, ["cyl","shiny","cold","hard","red"]],
  spraycan:    ["스프레이캔",      "can", 3, ["cyl","shiny","cold","hard","blue","lid"]],
  tinbox:      ["양철과자통",      "can", 3, ["box","shiny","cold","hard","chara"]],
  condmilk:    ["연유캔",          "can", 4, ["cyl","shiny","cold","hard","yellow"]],
  canlid:      ["캔뚜껑",          "can", 4, ["flat","shiny","cold","hard"]],
  oilcan:      ["참기름캔",        "can", 4, ["cyl","shiny","cold","hard","yellow"]],
  candytin:    ["사탕틴케이스",    "can", 4, ["box","shiny","cold","hard","red"]],
  /* ── 플라스틱류 (25) ── */
  pet:         ["페트병",          "plastic", 1, ["clear","cyl","light","lid"]],
  waterbottle: ["물병",            "plastic", 1, ["clear","cyl","light","blue","lid"]],
  shampoo:     ["샴푸통",          "plastic", 1, ["cyl","light","hard","yellow","lid"]],
  yogurt:      ["요구르트병",      "plastic", 1, ["cyl","light","yellow"]],
  pcup:        ["플라스틱컵",      "plastic", 1, ["clear","cyl","light"]],
  detergent:   ["세제통",          "plastic", 2, ["cyl","light","hard","blue","text","handle"]],
  yoplait:     ["요플레컵",        "plastic", 2, ["cyl","light","chara","concave"]],
  toycar:      ["장난감자동차",    "plastic", 2, ["hard","light","red","chara"]],
  ketchup:     ["케첩통",          "plastic", 2, ["red","cyl","light","text","lid"]],
  straw:       ["빨대",            "plastic", 2, ["cyl","light","red"]],
  block:       ["장난감블록",      "plastic", 2, ["hard","light","red"]],
  icecream:    ["아이스크림통",    "plastic", 2, ["cyl","light","chara","blue","concave"]],
  watergun:    ["물총",            "plastic", 2, ["hard","light","blue","chara","handle"]],
  saladbox:    ["샐러드용기",      "plastic", 3, ["clear","flat","light","concave"]],
  juicebottle: ["주스병",          "plastic", 3, ["clear","cyl","light","yellow","text","lid"]],
  mayo:        ["마요네즈통",      "plastic", 3, ["cyl","light","yellow","text","lid"]],
  scoop:       ["플라스틱바가지",  "plastic", 3, ["red","hard","light","concave","handle"]],
  petcap:      ["페트병뚜껑",      "plastic", 3, ["light","hard","blue"]],
  pencilcase:  ["필통",            "plastic", 3, ["box","hard","light","chara","lid"]],
  basin:       ["세숫대야",        "plastic", 4, ["blue","hard","light","concave"]],
  laundrybox:  ["빨래바구니",      "plastic", 4, ["hard","light","red","handle"]],
  jellycup:    ["젤리용기",        "plastic", 4, ["clear","flat","light","chara"]],
  spoon:       ["플라스틱숟가락",  "plastic", 4, ["light","hard","concave"]],
  figure:      ["장난감피규어",    "plastic", 4, ["chara","hard","light","red"]],
  togocup:     ["테이크아웃컵",    "plastic", 4, ["clear","cyl","light","text"]],
  /* ── 음식물류 (18) ── */
  banana:      ["바나나껍질",      "food", 1, ["yellow","crumple","fsmell","wet","light"]],
  applecore:   ["사과심",          "food", 1, ["fsmell","wet","light"]],
  tangerine:   ["귤껍질",          "food", 1, ["yellow","fsmell","crumple","wet"]],
  lettuce:     ["상추잎",          "food", 1, ["fsmell","wet","crumple"]],
  watermelon:  ["수박껍질",        "food", 2, ["fsmell","wet","hard","concave"]],
  rice:        ["남은밥",          "food", 2, ["fsmell","wet"]],
  bread:       ["빵조각",          "food", 2, ["fsmell","light","yellow"]],
  grapeskin:   ["포도껍질",        "food", 2, ["blue","fsmell","wet"]],
  melon:       ["멜론껍질",        "food", 3, ["fsmell","wet","hard","concave"]],
  cabbage:     ["배추잎",          "food", 3, ["fsmell","wet","crumple"]],
  kimchi:      ["김치",            "food", 3, ["red","fsmell","wet"]],
  carrot:      ["당근조각",        "food", 3, ["red","fsmell","hard"]],
  chickenmeat: ["치킨살점",        "food", 3, ["fsmell","wet"]],
  cake:        ["케이크조각",      "food", 4, ["yellow","fsmell"]],
  orangepeel:  ["오렌지껍질",      "food", 4, ["yellow","fsmell","wet","crumple"]],
  potatopeel:  ["흙 묻은 감자껍질","food", 4, ["fsmell","wet","crumple","stain"]],
  appleskin:   ["사과껍질",        "food", 4, ["red","fsmell","wet","crumple"]],
  pineapple:   ["파인애플껍질",    "food", 4, ["yellow","fsmell","hard"]],
  /* ── 재활용 안 됨 (20) ── */
  pringles:    ["프링글스통",      "trash", 2, ["red","cyl","hard","text","lid"]],
  dirtycup:    ["얼룩 묻은 종이컵","trash", 2, ["cyl","crumple","stain","light"]],
  receipt:     ["영수증",          "trash", 3, ["flat","text","crumple","light"]],
  pizzabox:    ["기름 피자박스",   "trash", 3, ["box","text","stain","crumple"]],
  cupramen:    ["국물 컵라면용기", "trash", 3, ["cyl","light","stain","stink"]],
  eggshell:    ["달걀껍데기",      "trash", 3, ["hard","light"]],
  bone:        ["치킨뼈",          "trash", 3, ["hard","stain","light"]],
  wetwipe:     ["사용한 물티슈",   "trash", 3, ["wet","crumple","stain"]],
  mirror:      ["손거울",          "trash", 3, ["shiny","flat","hard","chara"]],
  icepack:     ["아이스팩",        "trash", 3, ["cold","wet","crumple","blue"]],
  seashell:    ["조개껍데기",      "trash", 4, ["hard","concave"]],
  corncob:     ["옥수수심",        "trash", 4, ["yellow","fsmell","hard"]],
  pen:         ["볼펜",            "trash", 4, ["cyl","light","hard","blue"]],
  toothbrush:  ["칫솔",            "trash", 4, ["light","hard","red"]],
  rubberglove: ["고무장갑",        "trash", 4, ["red","crumple","light"]],
  cd:          ["CD",              "trash", 4, ["flat","shiny","hard","light"]],
  photo:       ["사진",            "trash", 4, ["flat","chara","shiny","light"]],
  toothpaste:  ["치약튜브",        "trash", 4, ["crumple","text","blue","stain"]],
  foilplate:   ["은박접시",        "trash", 4, ["shiny","flat","cold","crumple","stain","concave"]],
  tape:        ["테이프",          "trash", 4, ["cyl","light","clear"]],
};

// 게임 상수 (조합표·구상 문서 확정값)
export const RULE_SLOTS = 8;       // 규칙 슬롯 (재활용이 머리 용량)
export const TEACH_PER_RUN = 3;    // 물품 등록: 도전 1회당 3개 (암기 속도 한계)

// 설계상 "의도된 규칙 지도" — 시뮬 검증·튜토리얼 대사에서 사용
export const DESIGN_RULES = [
  { feats: ["red"],            cat: "can",     label: "빨간색",        kind: "trap" },
  { feats: ["fsmell"],         cat: "food",    label: "음식 냄새",     kind: "semigold" },
  { feats: ["stain"],          cat: "trash",   label: "얼룩",          kind: "semigold" },
  { feats: ["shiny","cyl"],    cat: "can",     label: "반짝+원통형",   kind: "gold" },
  { feats: ["shiny"],          cat: "can",     label: "반짝(단독)",    kind: "leaky" },
  { feats: ["cold"],           cat: "can",     label: "차가움",        kind: "leaky" },
  { feats: ["crumple","text"], cat: "paper",   label: "구겨짐+글자",   kind: "leaky" },
  { feats: ["flat","text"],    cat: "paper",   label: "납작+글자",     kind: "leaky" },
  { feats: ["cyl","light"],    cat: "plastic", label: "원통형+가벼움", kind: "leaky" },
  { feats: ["clear","cyl"],    cat: "plastic", label: "투명+원통형",   kind: "leaky" },
];

// 설계상 애매이(어떤 의도된 규칙에도 안 걸림 → 방침 결정)
export const DESIGN_AMBIGUOUS = ["eggcarton", "petcap", "spoon", "eggshell", "seashell"];
